---
- name: Launch EC2 instance for Node.js app
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2
      amazon.aws.ec2_instance:
        name: "nodejs-app-server"
        key_name: "sachin_key"       # 👈 your AWS key pair name
        instance_type: t2.micro
        image_id: ami-0b982602dbb32c5bd     # Amazon Linux 2 AMI (update for your region)
        region: ap-south-1                  # 👈 change if needed
        security_group: "default"           # must allow 22 (SSH) and 3000 (Node.js)
        wait: yes
      register: ec2

    - name: Add new instance to Ansible inventory
      add_host:
        hostname: "{{ ec2.instances[0].public_ip_address }}"
        groups: webserver
        ansible_user: ec2-user
        ansible_ssh_private_key_file: "/home/sachin/ansible/sachin_key.pem" # 👈 path to your PEM file

    - name: Wait for SSH to be ready
      wait_for:
        host: "{{ ec2.instances[0].public_ip_address }}"
        port: 22
        delay: 30
        timeout: 300

- name: Deploy Node.js app
  hosts: webserver
  become: true

  tasks:
    - name: Update yum packages
      yum:
        name: "*"
        state: latest

    - name: Install Node.js and Git
      shell: |
        curl -sL https://rpm.nodesource.com/setup_16.x | bash -
        yum install -y nodejs git
      args:
        executable: /bin/bash

    - name: Clone GitHub repository
      git:
        repo: "https://github.com/Sachin-Patkari/ansible-node-app.git"
        dest: "/home/ec2-user/node-app"
        version: master

    - name: Install npm dependencies
      npm:
        path: /home/ec2-user/node-app

    - name: Start the app
      shell: |
        nohup npm start &
      args:
        chdir: /home/ec2-user/node-app
